const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE';
const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';

export {
    NAVIGATE_TO_PAGE,
    LOAD_PRODUCTS_REQUEST,
    LOAD_PRODUCTS_SUCCESS
}
